// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "flow.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* flow_t_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  flow_t_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_flow_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  const ::google::protobuf::FileDescriptor* file = pool->InternalBuildGeneratedFile(
    "\n\nflow.proto\"\367\001\n\006flow_t\022\r\n\005proto\030\001 \002(\r\022\023"
    "\n\013class_proto\030\002 \002(\r\022\016\n\006src_if\030\003 \002(\t\022\016\n\006d"
    "st_if\030\004 \002(\t\022\020\n\010src_port\030\005 \002(\r\022\020\n\010dst_por"
    "t\030\006 \002(\r\022\017\n\007n_bytes\030\007 \002(\r\022\020\n\010n_frames\030\010 \002"
    "(\r\022\017\n\007ini_sec\030\t \002(\r\022\017\n\007ini_mic\030\n \002(\r\022\017\n\007"
    "end_sec\030\013 \002(\r\022\017\n\007end_mic\030\014 \002(\r\022\016\n\006src_ip"
    "\030\r \002(\r\022\016\n\006dst_ip\030\016 \002(\r", 262);
  flow_t_descriptor_ = file->message_type(0);
  flow_t_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      flow_t_descriptor_,
      &flow_t::default_instance(),
      flow_t::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    flow_t_descriptor_, &flow_t::default_instance());
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_flow_2eproto {
  StaticDescriptorInitializer_flow_2eproto() {
    protobuf_BuildDesc_flow_2eproto();
  }
} static_descriptor_initializer_flow_2eproto_;


// ===================================================================

const flow_t flow_t::default_instance_;



const ::std::string flow_t::_default_src_if_;
const ::std::string flow_t::_default_dst_if_;










const int flow_t::_offsets_[14] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, proto_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, class_proto_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, src_if_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, dst_if_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, src_port_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, dst_port_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, n_bytes_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, n_frames_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, ini_sec_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, ini_mic_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, end_sec_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, end_mic_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, src_ip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_t, dst_ip_),
};

flow_t::flow_t()
  : _cached_size_(0),
    proto_(0u),
    class_proto_(0u),
    src_if_(const_cast< ::std::string*>(&_default_src_if_)),
    dst_if_(const_cast< ::std::string*>(&_default_dst_if_)),
    src_port_(0u),
    dst_port_(0u),
    n_bytes_(0u),
    n_frames_(0u),
    ini_sec_(0u),
    ini_mic_(0u),
    end_sec_(0u),
    end_mic_(0u),
    src_ip_(0u),
    dst_ip_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (this == &default_instance_) {
  }
}

flow_t::flow_t(const flow_t& from)
  : _cached_size_(0),
    proto_(0u),
    class_proto_(0u),
    src_if_(const_cast< ::std::string*>(&_default_src_if_)),
    dst_if_(const_cast< ::std::string*>(&_default_dst_if_)),
    src_port_(0u),
    dst_port_(0u),
    n_bytes_(0u),
    n_frames_(0u),
    ini_sec_(0u),
    ini_mic_(0u),
    end_sec_(0u),
    end_mic_(0u),
    src_ip_(0u),
    dst_ip_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

flow_t::~flow_t() {
  if (src_if_ != &_default_src_if_) {
    delete src_if_;
  }
  if (dst_if_ != &_default_dst_if_) {
    delete dst_if_;
  }
  if (this != &default_instance_) {
  }
}

const ::google::protobuf::Descriptor* flow_t::descriptor() {
  if (flow_t_descriptor_ == NULL) protobuf_BuildDesc_flow_2eproto();
  return flow_t_descriptor_;
}

flow_t* flow_t::New() const {
  return new flow_t;
}

const ::google::protobuf::Descriptor* flow_t::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* flow_t::GetReflection() const {
  if (flow_t_reflection_ == NULL) protobuf_BuildDesc_flow_2eproto();
  return flow_t_reflection_;
}
