// Generated by the protocol buffer compiler.  DO NOT EDIT!

#ifndef PROTOBUF_packetDigest_2eproto__INCLUDED
#define PROTOBUF_packetDigest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>

class packet_digest;

// ===================================================================

class packet_digest : public ::google::protobuf::Message {
 public:
  packet_digest();
  virtual ~packet_digest();
  
  packet_digest(const packet_digest& from);
  
  inline packet_digest& operator=(const packet_digest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline static const packet_digest& default_instance() {
    return default_instance_;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _reflection_.unknown_fields();
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _reflection_.mutable_unknown_fields();
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  
  // implements Message ----------------------------------------------
  
  packet_digest* New() const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SetCachedSize(int size) const { _cached_size_ = size; }
  public:
  
  const ::google::protobuf::Descriptor* GetDescriptor() const;
  const ::google::protobuf::Message::Reflection* GetReflection() const;
  ::google::protobuf::Message::Reflection* GetReflection();
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 time_stamp = 1;
  inline bool has_time_stamp() const;
  inline void clear_time_stamp();
  inline ::google::protobuf::uint32 time_stamp() const;
  inline void set_time_stamp(::google::protobuf::uint32 value);
  
  // required uint32 src_addr = 2;
  inline bool has_src_addr() const;
  inline void clear_src_addr();
  inline ::google::protobuf::uint32 src_addr() const;
  inline void set_src_addr(::google::protobuf::uint32 value);
  
  // required uint32 dst_addr = 3;
  inline bool has_dst_addr() const;
  inline void clear_dst_addr();
  inline ::google::protobuf::uint32 dst_addr() const;
  inline void set_dst_addr(::google::protobuf::uint32 value);
  
  // required uint32 packet_size = 4;
  inline bool has_packet_size() const;
  inline void clear_packet_size();
  inline ::google::protobuf::uint32 packet_size() const;
  inline void set_packet_size(::google::protobuf::uint32 value);
  
  // required uint32 protocol = 5;
  inline bool has_protocol() const;
  inline void clear_protocol();
  inline ::google::protobuf::uint32 protocol() const;
  inline void set_protocol(::google::protobuf::uint32 value);
  
  // required uint32 protocol_class = 6;
  inline bool has_protocol_class() const;
  inline void clear_protocol_class();
  inline ::google::protobuf::uint32 protocol_class() const;
  inline void set_protocol_class(::google::protobuf::uint32 value);
  
 private:
  ::google::protobuf::internal::GeneratedMessageReflection _reflection_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 time_stamp_;
  ::google::protobuf::uint32 src_addr_;
  ::google::protobuf::uint32 dst_addr_;
  ::google::protobuf::uint32 packet_size_;
  ::google::protobuf::uint32 protocol_;
  ::google::protobuf::uint32 protocol_class_;
  
  static const packet_digest default_instance_;
  static const int _offsets_[6];
  
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
};
// ===================================================================


// ===================================================================


// ===================================================================

// packet_digest

// required uint32 time_stamp = 1;
inline bool packet_digest::has_time_stamp() const {
  return _has_bit(0);
}
inline void packet_digest::clear_time_stamp() {
  time_stamp_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 packet_digest::time_stamp() const {
  return time_stamp_;
}
inline void packet_digest::set_time_stamp(::google::protobuf::uint32 value) {
  _set_bit(0);
  time_stamp_ = value;
}

// required uint32 src_addr = 2;
inline bool packet_digest::has_src_addr() const {
  return _has_bit(1);
}
inline void packet_digest::clear_src_addr() {
  src_addr_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 packet_digest::src_addr() const {
  return src_addr_;
}
inline void packet_digest::set_src_addr(::google::protobuf::uint32 value) {
  _set_bit(1);
  src_addr_ = value;
}

// required uint32 dst_addr = 3;
inline bool packet_digest::has_dst_addr() const {
  return _has_bit(2);
}
inline void packet_digest::clear_dst_addr() {
  dst_addr_ = 0u;
  _clear_bit(2);
}
inline ::google::protobuf::uint32 packet_digest::dst_addr() const {
  return dst_addr_;
}
inline void packet_digest::set_dst_addr(::google::protobuf::uint32 value) {
  _set_bit(2);
  dst_addr_ = value;
}

// required uint32 packet_size = 4;
inline bool packet_digest::has_packet_size() const {
  return _has_bit(3);
}
inline void packet_digest::clear_packet_size() {
  packet_size_ = 0u;
  _clear_bit(3);
}
inline ::google::protobuf::uint32 packet_digest::packet_size() const {
  return packet_size_;
}
inline void packet_digest::set_packet_size(::google::protobuf::uint32 value) {
  _set_bit(3);
  packet_size_ = value;
}

// required uint32 protocol = 5;
inline bool packet_digest::has_protocol() const {
  return _has_bit(4);
}
inline void packet_digest::clear_protocol() {
  protocol_ = 0u;
  _clear_bit(4);
}
inline ::google::protobuf::uint32 packet_digest::protocol() const {
  return protocol_;
}
inline void packet_digest::set_protocol(::google::protobuf::uint32 value) {
  _set_bit(4);
  protocol_ = value;
}

// required uint32 protocol_class = 6;
inline bool packet_digest::has_protocol_class() const {
  return _has_bit(5);
}
inline void packet_digest::clear_protocol_class() {
  protocol_class_ = 0u;
  _clear_bit(5);
}
inline ::google::protobuf::uint32 packet_digest::protocol_class() const {
  return protocol_class_;
}
inline void packet_digest::set_protocol_class(::google::protobuf::uint32 value) {
  _set_bit(5);
  protocol_class_ = value;
}

#endif  // PROTOBUF_packetDigest_2eproto__INCLUDED
