//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It defines the methods to contact a person or an organization. It includes phones, fax, pager, emails, web site and postal address. A noticeable thing is that the first email in sequence is regarded as the main email address, and the second one, if existing, acts as a backup email
 * 
 * <p>Java class for ContactMethodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactMethodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Phone" type="{http://www.ibm.com}PhoneNumberType" maxOccurs="3"/>
 *         &lt;element name="Fax" type="{http://www.ibm.com}PhoneNumberType" minOccurs="0"/>
 *         &lt;element name="Pager" type="{http://www.ibm.com}PhoneNumberType" minOccurs="0"/>
 *         &lt;element name="InternetEmailAddress" type="{http://www.ibm.com}InternetEmailAddressType" maxOccurs="2"/>
 *         &lt;element name="InternetWebAddress" type="{http://www.ibm.com}InternetWebAddressType" minOccurs="0"/>
 *         &lt;element name="Postal" type="{http://www.ibm.com}PostalType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactMethodType", propOrder = {
    "phone",
    "fax",
    "pager",
    "internetEmailAddress",
    "internetWebAddress",
    "postal"
})
public class ContactMethodType {

    @XmlElement(name = "Phone", required = true)
    protected List<PhoneNumberType> phone;
    @XmlElement(name = "Fax")
    protected PhoneNumberType fax;
    @XmlElement(name = "Pager")
    protected PhoneNumberType pager;
    @XmlElement(name = "InternetEmailAddress", required = true)
    protected List<String> internetEmailAddress;
    @XmlElement(name = "InternetWebAddress")
    protected String internetWebAddress;
    @XmlElement(name = "Postal")
    protected PostalType postal;

    /**
     * Gets the value of the phone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhoneNumberType }
     * 
     * 
     */
    public List<PhoneNumberType> getPhone() {
        if (phone == null) {
            phone = new ArrayList<PhoneNumberType>();
        }
        return this.phone;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneNumberType }
     *     
     */
    public PhoneNumberType getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneNumberType }
     *     
     */
    public void setFax(PhoneNumberType value) {
        this.fax = value;
    }

    /**
     * Gets the value of the pager property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneNumberType }
     *     
     */
    public PhoneNumberType getPager() {
        return pager;
    }

    /**
     * Sets the value of the pager property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneNumberType }
     *     
     */
    public void setPager(PhoneNumberType value) {
        this.pager = value;
    }

    /**
     * Gets the value of the internetEmailAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internetEmailAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInternetEmailAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInternetEmailAddress() {
        if (internetEmailAddress == null) {
            internetEmailAddress = new ArrayList<String>();
        }
        return this.internetEmailAddress;
    }

    /**
     * Gets the value of the internetWebAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternetWebAddress() {
        return internetWebAddress;
    }

    /**
     * Sets the value of the internetWebAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternetWebAddress(String value) {
        this.internetWebAddress = value;
    }

    /**
     * Gets the value of the postal property.
     * 
     * @return
     *     possible object is
     *     {@link PostalType }
     *     
     */
    public PostalType getPostal() {
        return postal;
    }

    /**
     * Sets the value of the postal property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostalType }
     *     
     */
    public void setPostal(PostalType value) {
        this.postal = value;
    }

}
