//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It describes a candidate's information about a kind of language, including the language name, his level, and references to corresponding language qualifications.
 * 
 * <p>Java class for LanguageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LanguageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LanguageName" type="{http://www.ibm.com}LanguageNameType"/>
 *         &lt;element name="Level" type="{http://www.ibm.com}SkillLevelType"/>
 *         &lt;element name="QualificationReference" type="{http://www.ibm.com}QualificationReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LanguageType", propOrder = {
    "languageName",
    "level",
    "qualificationReference"
})
public class LanguageType {

    @XmlElement(name = "LanguageName", required = true)
    protected String languageName;
    @XmlElement(name = "Level", required = true)
    protected SkillLevelType level;
    @XmlElement(name = "QualificationReference")
    protected List<QualificationReferenceType> qualificationReference;

    /**
     * Gets the value of the languageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageName() {
        return languageName;
    }

    /**
     * Sets the value of the languageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageName(String value) {
        this.languageName = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link SkillLevelType }
     *     
     */
    public SkillLevelType getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkillLevelType }
     *     
     */
    public void setLevel(SkillLevelType value) {
        this.level = value;
    }

    /**
     * Gets the value of the qualificationReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualificationReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualificationReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualificationReferenceType }
     * 
     * 
     */
    public List<QualificationReferenceType> getQualificationReference() {
        if (qualificationReference == null) {
            qualificationReference = new ArrayList<QualificationReferenceType>();
        }
        return this.qualificationReference;
    }

}
