//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It describes a professional training, such as the training name, provider, etc.
 * 
 * <p>Java class for ProfessionalTrainingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProfessionalTrainingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrainingName" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="TrainingProvider" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="TrainingSite" type="{http://www.ibm.com}NameType" minOccurs="0"/>
 *         &lt;element name="Duration" type="{http://www.ibm.com}DurationType"/>
 *         &lt;element name="DemonstratedSkills" type="{http://www.ibm.com}DemonstratedSkillsType" minOccurs="0"/>
 *         &lt;element name="QualificationReference" type="{http://www.ibm.com}QualificationReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProfessionalTrainingType", propOrder = {
    "trainingName",
    "trainingProvider",
    "trainingSite",
    "duration",
    "demonstratedSkills",
    "qualificationReference"
})
public class ProfessionalTrainingType {

    @XmlElement(name = "TrainingName", required = true)
    protected String trainingName;
    @XmlElement(name = "TrainingProvider", required = true)
    protected String trainingProvider;
    @XmlElement(name = "TrainingSite")
    protected String trainingSite;
    @XmlElement(name = "Duration", required = true)
    protected DurationType duration;
    @XmlElement(name = "DemonstratedSkills")
    protected DemonstratedSkillsType demonstratedSkills;
    @XmlElement(name = "QualificationReference")
    protected List<QualificationReferenceType> qualificationReference;

    /**
     * Gets the value of the trainingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainingName() {
        return trainingName;
    }

    /**
     * Sets the value of the trainingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainingName(String value) {
        this.trainingName = value;
    }

    /**
     * Gets the value of the trainingProvider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainingProvider() {
        return trainingProvider;
    }

    /**
     * Sets the value of the trainingProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainingProvider(String value) {
        this.trainingProvider = value;
    }

    /**
     * Gets the value of the trainingSite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainingSite() {
        return trainingSite;
    }

    /**
     * Sets the value of the trainingSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainingSite(String value) {
        this.trainingSite = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link DurationType }
     *     
     */
    public DurationType getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationType }
     *     
     */
    public void setDuration(DurationType value) {
        this.duration = value;
    }

    /**
     * Gets the value of the demonstratedSkills property.
     * 
     * @return
     *     possible object is
     *     {@link DemonstratedSkillsType }
     *     
     */
    public DemonstratedSkillsType getDemonstratedSkills() {
        return demonstratedSkills;
    }

    /**
     * Sets the value of the demonstratedSkills property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemonstratedSkillsType }
     *     
     */
    public void setDemonstratedSkills(DemonstratedSkillsType value) {
        this.demonstratedSkills = value;
    }

    /**
     * Gets the value of the qualificationReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualificationReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualificationReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualificationReferenceType }
     * 
     * 
     */
    public List<QualificationReferenceType> getQualificationReference() {
        if (qualificationReference == null) {
            qualificationReference = new ArrayList<QualificationReferenceType>();
        }
        return this.qualificationReference;
    }

}
