//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It defines how to refer to the specified qualifications in the Qualification dimension. Consistent with the Qualification definition, here are five choice of reference.
 * 
 * <p>Java class for QualificationReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QualificationReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="AwardRef" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="CertificationRef" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="PatentRef" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="PublicationRef" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="SpecialityRef" type="{http://www.ibm.com}NameType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QualificationReferenceType", propOrder = {
    "awardRef",
    "certificationRef",
    "patentRef",
    "publicationRef",
    "specialityRef"
})
public class QualificationReferenceType {

    @XmlElement(name = "AwardRef")
    protected String awardRef;
    @XmlElement(name = "CertificationRef")
    protected String certificationRef;
    @XmlElement(name = "PatentRef")
    protected String patentRef;
    @XmlElement(name = "PublicationRef")
    protected String publicationRef;
    @XmlElement(name = "SpecialityRef")
    protected String specialityRef;

    /**
     * Gets the value of the awardRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardRef() {
        return awardRef;
    }

    /**
     * Sets the value of the awardRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardRef(String value) {
        this.awardRef = value;
    }

    /**
     * Gets the value of the certificationRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationRef() {
        return certificationRef;
    }

    /**
     * Sets the value of the certificationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationRef(String value) {
        this.certificationRef = value;
    }

    /**
     * Gets the value of the patentRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatentRef() {
        return patentRef;
    }

    /**
     * Sets the value of the patentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatentRef(String value) {
        this.patentRef = value;
    }

    /**
     * Gets the value of the publicationRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationRef() {
        return publicationRef;
    }

    /**
     * Sets the value of the publicationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationRef(String value) {
        this.publicationRef = value;
    }

    /**
     * Gets the value of the specialityRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialityRef() {
        return specialityRef;
    }

    /**
     * Sets the value of the specialityRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialityRef(String value) {
        this.specialityRef = value;
    }

}
