//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for SkillLevelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SkillLevelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Outstanding"/>
 *     &lt;enumeration value="AboveAverage"/>
 *     &lt;enumeration value="Normal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum SkillLevelType {

    @XmlEnumValue("Outstanding")
    OUTSTANDING("Outstanding"),
    @XmlEnumValue("AboveAverage")
    ABOVE_AVERAGE("AboveAverage"),
    @XmlEnumValue("Normal")
    NORMAL("Normal");
    private final String value;

    SkillLevelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SkillLevelType fromValue(String v) {
        for (SkillLevelType c: SkillLevelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
