//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It describes a social activity, including a brief description, time duration, played roles etc.
 * 
 * <p>Java class for SocialActivityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SocialActivityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActivityDescription">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.ibm.com}TextDescriptionType">
 *               &lt;maxLength value="256"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Duration" type="{http://www.ibm.com}DurationType"/>
 *         &lt;element name="Role" maxOccurs="unbounded">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="32"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DemonstratedSkills" type="{http://www.ibm.com}DemonstratedSkillsType" minOccurs="0"/>
 *         &lt;element name="QualificationReference" type="{http://www.ibm.com}QualificationReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SocialActivityType", propOrder = {
    "activityDescription",
    "duration",
    "role",
    "demonstratedSkills",
    "qualificationReference"
})
public class SocialActivityType {

    @XmlElement(name = "ActivityDescription", required = true)
    protected String activityDescription;
    @XmlElement(name = "Duration", required = true)
    protected DurationType duration;
    @XmlElement(name = "Role", required = true)
    protected List<String> role;
    @XmlElement(name = "DemonstratedSkills")
    protected DemonstratedSkillsType demonstratedSkills;
    @XmlElement(name = "QualificationReference")
    protected List<QualificationReferenceType> qualificationReference;

    /**
     * Gets the value of the activityDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityDescription() {
        return activityDescription;
    }

    /**
     * Sets the value of the activityDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityDescription(String value) {
        this.activityDescription = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link DurationType }
     *     
     */
    public DurationType getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationType }
     *     
     */
    public void setDuration(DurationType value) {
        this.duration = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the role property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRole() {
        if (role == null) {
            role = new ArrayList<String>();
        }
        return this.role;
    }

    /**
     * Gets the value of the demonstratedSkills property.
     * 
     * @return
     *     possible object is
     *     {@link DemonstratedSkillsType }
     *     
     */
    public DemonstratedSkillsType getDemonstratedSkills() {
        return demonstratedSkills;
    }

    /**
     * Sets the value of the demonstratedSkills property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemonstratedSkillsType }
     *     
     */
    public void setDemonstratedSkills(DemonstratedSkillsType value) {
        this.demonstratedSkills = value;
    }

    /**
     * Gets the value of the qualificationReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualificationReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualificationReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualificationReferenceType }
     * 
     * 
     */
    public List<QualificationReferenceType> getQualificationReference() {
        if (qualificationReference == null) {
            qualificationReference = new ArrayList<QualificationReferenceType>();
        }
        return this.qualificationReference;
    }

}
