//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It describes all kinds of certifications, including professional certification and language certification, such as IBM AIX Certification and TOFEL.
 * 
 * <p>Java class for CertificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CertificationTitle" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="CertificationGrantor" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="CertifiedDate" type="{http://www.ibm.com}FlexibleDates"/>
 *         &lt;element name="Score" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DemonstratedSkills" type="{http://www.ibm.com}DemonstratedSkillsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificationType", propOrder = {
    "certificationTitle",
    "certificationGrantor",
    "certifiedDate",
    "score",
    "demonstratedSkills"
})
public class CertificationType {

    @XmlElement(name = "CertificationTitle", required = true)
    protected String certificationTitle;
    @XmlElement(name = "CertificationGrantor", required = true)
    protected String certificationGrantor;
    @XmlElement(name = "CertifiedDate", required = true)
    protected FlexibleDates certifiedDate;
    @XmlElement(name = "Score")
    protected String score;
    @XmlElement(name = "DemonstratedSkills")
    protected DemonstratedSkillsType demonstratedSkills;

    /**
     * Gets the value of the certificationTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationTitle() {
        return certificationTitle;
    }

    /**
     * Sets the value of the certificationTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationTitle(String value) {
        this.certificationTitle = value;
    }

    /**
     * Gets the value of the certificationGrantor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationGrantor() {
        return certificationGrantor;
    }

    /**
     * Sets the value of the certificationGrantor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationGrantor(String value) {
        this.certificationGrantor = value;
    }

    /**
     * Gets the value of the certifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link FlexibleDates }
     *     
     */
    public FlexibleDates getCertifiedDate() {
        return certifiedDate;
    }

    /**
     * Sets the value of the certifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlexibleDates }
     *     
     */
    public void setCertifiedDate(FlexibleDates value) {
        this.certifiedDate = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScore(String value) {
        this.score = value;
    }

    /**
     * Gets the value of the demonstratedSkills property.
     * 
     * @return
     *     possible object is
     *     {@link DemonstratedSkillsType }
     *     
     */
    public DemonstratedSkillsType getDemonstratedSkills() {
        return demonstratedSkills;
    }

    /**
     * Sets the value of the demonstratedSkills property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemonstratedSkillsType }
     *     
     */
    public void setDemonstratedSkills(DemonstratedSkillsType value) {
        this.demonstratedSkills = value;
    }

}
