//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It describes a conference publication. It extends the PublicationType by adding the conference name and conference sponsors.
 * 
 * <p>Java class for ConferencePublicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConferencePublicationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com}PublicationType">
 *       &lt;sequence>
 *         &lt;element name="ConferenceName" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="ConferenceSponsor" type="{http://www.ibm.com}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConferencePublicationType", propOrder = {
    "conferenceName",
    "conferenceSponsor"
})
public class ConferencePublicationType
    extends PublicationType
{

    @XmlElement(name = "ConferenceName", required = true)
    protected String conferenceName;
    @XmlElement(name = "ConferenceSponsor")
    protected List<String> conferenceSponsor;

    /**
     * Gets the value of the conferenceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConferenceName() {
        return conferenceName;
    }

    /**
     * Sets the value of the conferenceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConferenceName(String value) {
        this.conferenceName = value;
    }

    /**
     * Gets the value of the conferenceSponsor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conferenceSponsor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConferenceSponsor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConferenceSponsor() {
        if (conferenceSponsor == null) {
            conferenceSponsor = new ArrayList<String>();
        }
        return this.conferenceSponsor;
    }

}
