//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It describes a degree, including its name and granted date.
 * 
 * <p>Java class for DegreeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DegreeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DegreeName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Doctor"/>
 *               &lt;enumeration value="Master"/>
 *               &lt;enumeration value="Bachelor"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DegreeDate" type="{http://www.ibm.com}FlexibleDates"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DegreeType", propOrder = {
    "degreeName",
    "degreeDate"
})
public class DegreeType {

    @XmlElement(name = "DegreeName", required = true)
    protected String degreeName;
    @XmlElement(name = "DegreeDate", required = true)
    protected FlexibleDates degreeDate;

    /**
     * Gets the value of the degreeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegreeName() {
        return degreeName;
    }

    /**
     * Sets the value of the degreeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegreeName(String value) {
        this.degreeName = value;
    }

    /**
     * Gets the value of the degreeDate property.
     * 
     * @return
     *     possible object is
     *     {@link FlexibleDates }
     *     
     */
    public FlexibleDates getDegreeDate() {
        return degreeDate;
    }

    /**
     * Sets the value of the degreeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlexibleDates }
     *     
     */
    public void setDegreeDate(FlexibleDates value) {
        this.degreeDate = value;
    }

}
