//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It specified skills demonstrated in a piece of experience, or a qualification. It includes both technical skills and non technical skills. For example, in a piece of project experience, both programming skill(technical) and leadership skill(non-technical) are demonstrated.
 * 
 * <p>Java class for DemonstratedSkillsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DemonstratedSkillsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TechnicalSkill" type="{http://www.ibm.com}TechSkillType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NonTechnicalSkill" type="{http://www.ibm.com}NonTechSkillType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DemonstratedSkillsType", propOrder = {
    "technicalSkill",
    "nonTechnicalSkill"
})
public class DemonstratedSkillsType {

    @XmlElement(name = "TechnicalSkill")
    protected List<TechSkillType> technicalSkill;
    @XmlElement(name = "NonTechnicalSkill")
    protected List<NonTechSkillType> nonTechnicalSkill;

    /**
     * Gets the value of the technicalSkill property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technicalSkill property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnicalSkill().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TechSkillType }
     * 
     * 
     */
    public List<TechSkillType> getTechnicalSkill() {
        if (technicalSkill == null) {
            technicalSkill = new ArrayList<TechSkillType>();
        }
        return this.technicalSkill;
    }

    /**
     * Gets the value of the nonTechnicalSkill property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nonTechnicalSkill property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNonTechnicalSkill().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonTechSkillType }
     * 
     * 
     */
    public List<NonTechSkillType> getNonTechnicalSkill() {
        if (nonTechnicalSkill == null) {
            nonTechnicalSkill = new ArrayList<NonTechSkillType>();
        }
        return this.nonTechnicalSkill;
    }

}
