//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It describes a candidate's experience, including his project experience, employment history, professional training and social activity experience. It should be noticed that there are two special elements in every experience, one is the DemonstratedSkills and the other is the QualificationReference. The DemonstratedSkills is used to specify what skills are demonstrated (applied in or acquired from) during the experience, and the QualificationReference is used to specify the qualifications which could prove your success during the experience. An important state is that the value of the QualificationReference element must refer to an item you inputted in the Qualifications dimension.
 * 
 * <p>Java class for ExperienceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExperienceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Project" type="{http://www.ibm.com}ProjectType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Employment" type="{http://www.ibm.com}EmploymentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProfessionalTraining" type="{http://www.ibm.com}ProfessionalTrainingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SocialActivity" type="{http://www.ibm.com}SocialActivityType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExperienceType", propOrder = {
    "project",
    "employment",
    "professionalTraining",
    "socialActivity"
})
public class ExperienceType {

    @XmlElement(name = "Project")
    protected List<ProjectType> project;
    @XmlElement(name = "Employment")
    protected List<EmploymentType> employment;
    @XmlElement(name = "ProfessionalTraining")
    protected List<ProfessionalTrainingType> professionalTraining;
    @XmlElement(name = "SocialActivity")
    protected List<SocialActivityType> socialActivity;

    /**
     * Gets the value of the project property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the project property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProjectType }
     * 
     * 
     */
    public List<ProjectType> getProject() {
        if (project == null) {
            project = new ArrayList<ProjectType>();
        }
        return this.project;
    }

    /**
     * Gets the value of the employment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the employment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmployment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmploymentType }
     * 
     * 
     */
    public List<EmploymentType> getEmployment() {
        if (employment == null) {
            employment = new ArrayList<EmploymentType>();
        }
        return this.employment;
    }

    /**
     * Gets the value of the professionalTraining property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the professionalTraining property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfessionalTraining().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfessionalTrainingType }
     * 
     * 
     */
    public List<ProfessionalTrainingType> getProfessionalTraining() {
        if (professionalTraining == null) {
            professionalTraining = new ArrayList<ProfessionalTrainingType>();
        }
        return this.professionalTraining;
    }

    /**
     * Gets the value of the socialActivity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the socialActivity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSocialActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SocialActivityType }
     * 
     * 
     */
    public List<SocialActivityType> getSocialActivity() {
        if (socialActivity == null) {
            socialActivity = new ArrayList<SocialActivityType>();
        }
        return this.socialActivity;
    }

}
