//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * it specifies the information of a patent, such as the patent name and number, filed date. At the end, a candidate could state his personal contribution for the patent.
 * 
 * <p>Java class for PatentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PatentName" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="PatentNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="32"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FiledDate" type="{http://www.ibm.com}FlexibleDates"/>
 *         &lt;element name="PersonalContributionDescription" type="{http://www.ibm.com}TextDescriptionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatentType", propOrder = {
    "patentName",
    "patentNo",
    "filedDate",
    "personalContributionDescription"
})
public class PatentType {

    @XmlElement(name = "PatentName", required = true)
    protected String patentName;
    @XmlElement(name = "PatentNo", required = true)
    protected String patentNo;
    @XmlElement(name = "FiledDate", required = true)
    protected FlexibleDates filedDate;
    @XmlElement(name = "PersonalContributionDescription")
    protected String personalContributionDescription;

    /**
     * Gets the value of the patentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatentName() {
        return patentName;
    }

    /**
     * Sets the value of the patentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatentName(String value) {
        this.patentName = value;
    }

    /**
     * Gets the value of the patentNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatentNo() {
        return patentNo;
    }

    /**
     * Sets the value of the patentNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatentNo(String value) {
        this.patentNo = value;
    }

    /**
     * Gets the value of the filedDate property.
     * 
     * @return
     *     possible object is
     *     {@link FlexibleDates }
     *     
     */
    public FlexibleDates getFiledDate() {
        return filedDate;
    }

    /**
     * Sets the value of the filedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlexibleDates }
     *     
     */
    public void setFiledDate(FlexibleDates value) {
        this.filedDate = value;
    }

    /**
     * Gets the value of the personalContributionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalContributionDescription() {
        return personalContributionDescription;
    }

    /**
     * Sets the value of the personalContributionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalContributionDescription(String value) {
        this.personalContributionDescription = value;
    }

}
