//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It describes a candidate's experience in a project. There is a required attribute isResearchProject to specify whether the project is a research project or not. 
 * 
 * <p>Java class for ProjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProjectName" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="ProjectDescription" type="{http://www.ibm.com}TextDescriptionType"/>
 *         &lt;element name="ProjectKeyword" maxOccurs="6" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Sponsor" type="{http://www.ibm.com}NameType" minOccurs="0"/>
 *         &lt;element name="PersonMonthScale" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RoleInProject" type="{http://www.ibm.com}RoleType" maxOccurs="unbounded"/>
 *         &lt;element name="Duration" type="{http://www.ibm.com}DurationType"/>
 *         &lt;element name="PersonalContributionDescription" type="{http://www.ibm.com}TextDescriptionType" minOccurs="0"/>
 *         &lt;element name="ReferencePerson" type="{http://www.ibm.com}ContactInfoType" minOccurs="0"/>
 *         &lt;element name="DemonstratedSkills" type="{http://www.ibm.com}DemonstratedSkillsType" minOccurs="0"/>
 *         &lt;element name="QualificationReference" type="{http://www.ibm.com}QualificationReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isResearchProject" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProjectType", propOrder = {
    "projectName",
    "projectDescription",
    "projectKeyword",
    "sponsor",
    "personMonthScale",
    "roleInProject",
    "duration",
    "personalContributionDescription",
    "referencePerson",
    "demonstratedSkills",
    "qualificationReference"
})
public class ProjectType {

    @XmlElement(name = "ProjectName", required = true)
    protected String projectName;
    @XmlElement(name = "ProjectDescription", required = true)
    protected String projectDescription;
    @XmlElement(name = "ProjectKeyword")
    protected List<String> projectKeyword;
    @XmlElement(name = "Sponsor")
    protected String sponsor;
    @XmlElement(name = "PersonMonthScale")
    protected Integer personMonthScale;
    @XmlElement(name = "RoleInProject", required = true)
    protected List<String> roleInProject;
    @XmlElement(name = "Duration", required = true)
    protected DurationType duration;
    @XmlElement(name = "PersonalContributionDescription")
    protected String personalContributionDescription;
    @XmlElement(name = "ReferencePerson")
    protected ContactInfoType referencePerson;
    @XmlElement(name = "DemonstratedSkills")
    protected DemonstratedSkillsType demonstratedSkills;
    @XmlElement(name = "QualificationReference")
    protected List<QualificationReferenceType> qualificationReference;
    @XmlAttribute(required = true)
    protected boolean isResearchProject;

    /**
     * Gets the value of the projectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectName(String value) {
        this.projectName = value;
    }

    /**
     * Gets the value of the projectDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * Sets the value of the projectDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectDescription(String value) {
        this.projectDescription = value;
    }

    /**
     * Gets the value of the projectKeyword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectKeyword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProjectKeyword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProjectKeyword() {
        if (projectKeyword == null) {
            projectKeyword = new ArrayList<String>();
        }
        return this.projectKeyword;
    }

    /**
     * Gets the value of the sponsor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSponsor() {
        return sponsor;
    }

    /**
     * Sets the value of the sponsor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSponsor(String value) {
        this.sponsor = value;
    }

    /**
     * Gets the value of the personMonthScale property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPersonMonthScale() {
        return personMonthScale;
    }

    /**
     * Sets the value of the personMonthScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPersonMonthScale(Integer value) {
        this.personMonthScale = value;
    }

    /**
     * Gets the value of the roleInProject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleInProject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleInProject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRoleInProject() {
        if (roleInProject == null) {
            roleInProject = new ArrayList<String>();
        }
        return this.roleInProject;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link DurationType }
     *     
     */
    public DurationType getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationType }
     *     
     */
    public void setDuration(DurationType value) {
        this.duration = value;
    }

    /**
     * Gets the value of the personalContributionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalContributionDescription() {
        return personalContributionDescription;
    }

    /**
     * Sets the value of the personalContributionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalContributionDescription(String value) {
        this.personalContributionDescription = value;
    }

    /**
     * Gets the value of the referencePerson property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfoType }
     *     
     */
    public ContactInfoType getReferencePerson() {
        return referencePerson;
    }

    /**
     * Sets the value of the referencePerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfoType }
     *     
     */
    public void setReferencePerson(ContactInfoType value) {
        this.referencePerson = value;
    }

    /**
     * Gets the value of the demonstratedSkills property.
     * 
     * @return
     *     possible object is
     *     {@link DemonstratedSkillsType }
     *     
     */
    public DemonstratedSkillsType getDemonstratedSkills() {
        return demonstratedSkills;
    }

    /**
     * Sets the value of the demonstratedSkills property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemonstratedSkillsType }
     *     
     */
    public void setDemonstratedSkills(DemonstratedSkillsType value) {
        this.demonstratedSkills = value;
    }

    /**
     * Gets the value of the qualificationReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualificationReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualificationReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualificationReferenceType }
     * 
     * 
     */
    public List<QualificationReferenceType> getQualificationReference() {
        if (qualificationReference == null) {
            qualificationReference = new ArrayList<QualificationReferenceType>();
        }
        return this.qualificationReference;
    }

    /**
     * Gets the value of the isResearchProject property.
     * 
     */
    public boolean isIsResearchProject() {
        return isResearchProject;
    }

    /**
     * Sets the value of the isResearchProject property.
     * 
     */
    public void setIsResearchProject(boolean value) {
        this.isResearchProject = value;
    }

}
