//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It specifies the common information of a publication, such as a title, publish date, etc.
 * 
 * <p>Java class for PublicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PublicationTitle" type="{http://www.ibm.com}NameType"/>
 *         &lt;element name="PublishDate" type="{http://www.ibm.com}FlexibleDates"/>
 *         &lt;element name="AuthorOrder">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PersonalContributionDescription" type="{http://www.ibm.com}TextDescriptionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicationType", propOrder = {
    "publicationTitle",
    "publishDate",
    "authorOrder",
    "personalContributionDescription"
})
public class PublicationType {

    @XmlElement(name = "PublicationTitle", required = true)
    protected String publicationTitle;
    @XmlElement(name = "PublishDate", required = true)
    protected FlexibleDates publishDate;
    @XmlElement(name = "AuthorOrder")
    protected int authorOrder;
    @XmlElement(name = "PersonalContributionDescription")
    protected String personalContributionDescription;

    /**
     * Gets the value of the publicationTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationTitle() {
        return publicationTitle;
    }

    /**
     * Sets the value of the publicationTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationTitle(String value) {
        this.publicationTitle = value;
    }

    /**
     * Gets the value of the publishDate property.
     * 
     * @return
     *     possible object is
     *     {@link FlexibleDates }
     *     
     */
    public FlexibleDates getPublishDate() {
        return publishDate;
    }

    /**
     * Sets the value of the publishDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlexibleDates }
     *     
     */
    public void setPublishDate(FlexibleDates value) {
        this.publishDate = value;
    }

    /**
     * Gets the value of the authorOrder property.
     * 
     */
    public int getAuthorOrder() {
        return authorOrder;
    }

    /**
     * Sets the value of the authorOrder property.
     * 
     */
    public void setAuthorOrder(int value) {
        this.authorOrder = value;
    }

    /**
     * Gets the value of the personalContributionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalContributionDescription() {
        return personalContributionDescription;
    }

    /**
     * Sets the value of the personalContributionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalContributionDescription(String value) {
        this.personalContributionDescription = value;
    }

}
