//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * It specifies a candidate's qualifications, which can demonstrate one's capability. It is result-oriented, including publication, patent, certification, award and speciality.
 * 
 * <p>Java class for QualificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QualificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Publication" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="JournalPublication" type="{http://www.ibm.com}JournalPublicationType"/>
 *                   &lt;element name="ConferencePublication" type="{http://www.ibm.com}ConferencePublicationType"/>
 *                   &lt;element name="Book" type="{http://www.ibm.com}BookType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Patent" type="{http://www.ibm.com}PatentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Certification" type="{http://www.ibm.com}CertificationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Award" type="{http://www.ibm.com}AwardType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Speciality" type="{http://www.ibm.com}SpecialityType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QualificationType", propOrder = {
    "publication",
    "patent",
    "certification",
    "award",
    "speciality"
})
public class QualificationType {

    @XmlElement(name = "Publication")
    protected List<QualificationType.Publication> publication;
    @XmlElement(name = "Patent")
    protected List<PatentType> patent;
    @XmlElement(name = "Certification")
    protected List<CertificationType> certification;
    @XmlElement(name = "Award")
    protected List<AwardType> award;
    @XmlElement(name = "Speciality")
    protected List<SpecialityType> speciality;

    /**
     * Gets the value of the publication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualificationType.Publication }
     * 
     * 
     */
    public List<QualificationType.Publication> getPublication() {
        if (publication == null) {
            publication = new ArrayList<QualificationType.Publication>();
        }
        return this.publication;
    }

    /**
     * Gets the value of the patent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatentType }
     * 
     * 
     */
    public List<PatentType> getPatent() {
        if (patent == null) {
            patent = new ArrayList<PatentType>();
        }
        return this.patent;
    }

    /**
     * Gets the value of the certification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the certification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCertification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CertificationType }
     * 
     * 
     */
    public List<CertificationType> getCertification() {
        if (certification == null) {
            certification = new ArrayList<CertificationType>();
        }
        return this.certification;
    }

    /**
     * Gets the value of the award property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the award property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAward().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AwardType }
     * 
     * 
     */
    public List<AwardType> getAward() {
        if (award == null) {
            award = new ArrayList<AwardType>();
        }
        return this.award;
    }

    /**
     * Gets the value of the speciality property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the speciality property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpeciality().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecialityType }
     * 
     * 
     */
    public List<SpecialityType> getSpeciality() {
        if (speciality == null) {
            speciality = new ArrayList<SpecialityType>();
        }
        return this.speciality;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="JournalPublication" type="{http://www.ibm.com}JournalPublicationType"/>
     *         &lt;element name="ConferencePublication" type="{http://www.ibm.com}ConferencePublicationType"/>
     *         &lt;element name="Book" type="{http://www.ibm.com}BookType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "journalPublication",
        "conferencePublication",
        "book"
    })
    public static class Publication {

        @XmlElement(name = "JournalPublication")
        protected JournalPublicationType journalPublication;
        @XmlElement(name = "ConferencePublication")
        protected ConferencePublicationType conferencePublication;
        @XmlElement(name = "Book")
        protected BookType book;

        /**
         * Gets the value of the journalPublication property.
         * 
         * @return
         *     possible object is
         *     {@link JournalPublicationType }
         *     
         */
        public JournalPublicationType getJournalPublication() {
            return journalPublication;
        }

        /**
         * Sets the value of the journalPublication property.
         * 
         * @param value
         *     allowed object is
         *     {@link JournalPublicationType }
         *     
         */
        public void setJournalPublication(JournalPublicationType value) {
            this.journalPublication = value;
        }

        /**
         * Gets the value of the conferencePublication property.
         * 
         * @return
         *     possible object is
         *     {@link ConferencePublicationType }
         *     
         */
        public ConferencePublicationType getConferencePublication() {
            return conferencePublication;
        }

        /**
         * Sets the value of the conferencePublication property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConferencePublicationType }
         *     
         */
        public void setConferencePublication(ConferencePublicationType value) {
            this.conferencePublication = value;
        }

        /**
         * Gets the value of the book property.
         * 
         * @return
         *     possible object is
         *     {@link BookType }
         *     
         */
        public BookType getBook() {
            return book;
        }

        /**
         * Sets the value of the book property.
         * 
         * @param value
         *     allowed object is
         *     {@link BookType }
         *     
         */
        public void setBook(BookType value) {
            this.book = value;
        }

    }

}
