//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContactInfo" type="{http://www.ibm.com}ContactInfoType"/>
 *         &lt;element name="OnBoardAvailability" type="{http://www.w3.org/2001/XMLSchema}gYearMonth"/>
 *         &lt;element name="Objectives">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Objective" type="{http://www.ibm.com}ObjectiveType" maxOccurs="4"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EducationHistory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Education" type="{http://www.ibm.com}EducationType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Languages" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Language" type="{http://www.ibm.com}LanguageType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Experience" type="{http://www.ibm.com}ExperienceType" minOccurs="0"/>
 *         &lt;element name="Qualifications" type="{http://www.ibm.com}QualificationType" minOccurs="0"/>
 *         &lt;element name="ProfessionalAssociations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ProfessionalAssociation" type="{http://www.ibm.com}ProfessionalAssociationType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Summary" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contactInfo",
    "onBoardAvailability",
    "objectives",
    "educationHistory",
    "languages",
    "experience",
    "qualifications",
    "professionalAssociations",
    "summary"
})
@XmlRootElement(name = "Resume")
public class Resume {

    @XmlElement(name = "ContactInfo", required = true)
    protected ContactInfoType contactInfo;
    @XmlElement(name = "OnBoardAvailability", required = true)
    protected XMLGregorianCalendar onBoardAvailability;
    @XmlElement(name = "Objectives", required = true)
    protected Resume.Objectives objectives;
    @XmlElement(name = "EducationHistory", required = true)
    protected Resume.EducationHistory educationHistory;
    @XmlElement(name = "Languages")
    protected Resume.Languages languages;
    @XmlElement(name = "Experience")
    protected ExperienceType experience;
    @XmlElement(name = "Qualifications")
    protected QualificationType qualifications;
    @XmlElement(name = "ProfessionalAssociations")
    protected Resume.ProfessionalAssociations professionalAssociations;
    @XmlElement(name = "Summary")
    protected String summary;

    /**
     * Gets the value of the contactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfoType }
     *     
     */
    public ContactInfoType getContactInfo() {
        return contactInfo;
    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfoType }
     *     
     */
    public void setContactInfo(ContactInfoType value) {
        this.contactInfo = value;
    }

    /**
     * Gets the value of the onBoardAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOnBoardAvailability() {
        return onBoardAvailability;
    }

    /**
     * Sets the value of the onBoardAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOnBoardAvailability(XMLGregorianCalendar value) {
        this.onBoardAvailability = value;
    }

    /**
     * Gets the value of the objectives property.
     * 
     * @return
     *     possible object is
     *     {@link Resume.Objectives }
     *     
     */
    public Resume.Objectives getObjectives() {
        return objectives;
    }

    /**
     * Sets the value of the objectives property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resume.Objectives }
     *     
     */
    public void setObjectives(Resume.Objectives value) {
        this.objectives = value;
    }

    /**
     * Gets the value of the educationHistory property.
     * 
     * @return
     *     possible object is
     *     {@link Resume.EducationHistory }
     *     
     */
    public Resume.EducationHistory getEducationHistory() {
        return educationHistory;
    }

    /**
     * Sets the value of the educationHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resume.EducationHistory }
     *     
     */
    public void setEducationHistory(Resume.EducationHistory value) {
        this.educationHistory = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link Resume.Languages }
     *     
     */
    public Resume.Languages getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resume.Languages }
     *     
     */
    public void setLanguages(Resume.Languages value) {
        this.languages = value;
    }

    /**
     * Gets the value of the experience property.
     * 
     * @return
     *     possible object is
     *     {@link ExperienceType }
     *     
     */
    public ExperienceType getExperience() {
        return experience;
    }

    /**
     * Sets the value of the experience property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperienceType }
     *     
     */
    public void setExperience(ExperienceType value) {
        this.experience = value;
    }

    /**
     * Gets the value of the qualifications property.
     * 
     * @return
     *     possible object is
     *     {@link QualificationType }
     *     
     */
    public QualificationType getQualifications() {
        return qualifications;
    }

    /**
     * Sets the value of the qualifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualificationType }
     *     
     */
    public void setQualifications(QualificationType value) {
        this.qualifications = value;
    }

    /**
     * Gets the value of the professionalAssociations property.
     * 
     * @return
     *     possible object is
     *     {@link Resume.ProfessionalAssociations }
     *     
     */
    public Resume.ProfessionalAssociations getProfessionalAssociations() {
        return professionalAssociations;
    }

    /**
     * Sets the value of the professionalAssociations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resume.ProfessionalAssociations }
     *     
     */
    public void setProfessionalAssociations(Resume.ProfessionalAssociations value) {
        this.professionalAssociations = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummary(String value) {
        this.summary = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Education" type="{http://www.ibm.com}EducationType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "education"
    })
    public static class EducationHistory {

        @XmlElement(name = "Education", required = true)
        protected List<EducationType> education;

        /**
         * Gets the value of the education property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the education property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEducation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EducationType }
         * 
         * 
         */
        public List<EducationType> getEducation() {
            if (education == null) {
                education = new ArrayList<EducationType>();
            }
            return this.education;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Language" type="{http://www.ibm.com}LanguageType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "language"
    })
    public static class Languages {

        @XmlElement(name = "Language")
        protected List<LanguageType> language;

        /**
         * Gets the value of the language property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the language property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LanguageType }
         * 
         * 
         */
        public List<LanguageType> getLanguage() {
            if (language == null) {
                language = new ArrayList<LanguageType>();
            }
            return this.language;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Objective" type="{http://www.ibm.com}ObjectiveType" maxOccurs="4"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "objective"
    })
    public static class Objectives {

        @XmlElement(name = "Objective", required = true)
        protected List<String> objective;

        /**
         * Gets the value of the objective property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the objective property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObjective().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getObjective() {
            if (objective == null) {
                objective = new ArrayList<String>();
            }
            return this.objective;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ProfessionalAssociation" type="{http://www.ibm.com}ProfessionalAssociationType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "professionalAssociation"
    })
    public static class ProfessionalAssociations {

        @XmlElement(name = "ProfessionalAssociation")
        protected List<ProfessionalAssociationType> professionalAssociation;

        /**
         * Gets the value of the professionalAssociation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the professionalAssociation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProfessionalAssociation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProfessionalAssociationType }
         * 
         * 
         */
        public List<ProfessionalAssociationType> getProfessionalAssociation() {
            if (professionalAssociation == null) {
                professionalAssociation = new ArrayList<ProfessionalAssociationType>();
            }
            return this.professionalAssociation;
        }

    }

}
