//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:08:09 PM CET 
//


package com.ibm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for RoleEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoleEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Manager"/>
 *     &lt;enumeration value="Architect"/>
 *     &lt;enumeration value="Designer"/>
 *     &lt;enumeration value="Tester"/>
 *     &lt;enumeration value="Coder"/>
 *     &lt;enumeration value="Analyzer"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum RoleEnumType {

    @XmlEnumValue("Manager")
    MANAGER("Manager"),
    @XmlEnumValue("Architect")
    ARCHITECT("Architect"),
    @XmlEnumValue("Designer")
    DESIGNER("Designer"),
    @XmlEnumValue("Tester")
    TESTER("Tester"),
    @XmlEnumValue("Coder")
    CODER("Coder"),
    @XmlEnumValue("Analyzer")
    ANALYZER("Analyzer");
    private final String value;

    RoleEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoleEnumType fromValue(String v) {
        for (RoleEnumType c: RoleEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
