// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "flowcollection.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>
void proto_BuildDescriptors_flow_2eproto();

namespace {

const ::google::protobuf::Descriptor* flow_collection_descriptor_ = NULL;

}  // namespace


void proto_BuildDescriptors_flowcollection_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  ::proto_BuildDescriptors_flow_2eproto();
  const ::google::protobuf::FileDescriptor* file = pool->InternalBuildGeneratedFile(
    "\n\024flowcollection.proto\032\nflow.proto\"(\n\017fl"
    "ow_collection\022\025\n\004flow\030\001 \003(\0132\007.flow_t", 76);
  flow_collection_descriptor_ = file->message_type(0);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    flow_collection_descriptor_, &flow_collection::default_instance());
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_flowcollection_2eproto {
  StaticDescriptorInitializer_flowcollection_2eproto() {
    proto_BuildDescriptors_flowcollection_2eproto();
  }
} static_descriptor_initializer_flowcollection_2eproto_;


// ===================================================================

const flow_collection flow_collection::default_instance_;


const int flow_collection::_offsets_[1] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(flow_collection, flow_),
};

flow_collection::flow_collection()
  : _reflection_(descriptor(),
                 this, &default_instance_,
                 _offsets_, _has_bits_, NULL),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (this == &default_instance_) {
  }
}

flow_collection::flow_collection(const flow_collection& from)
  : _reflection_(descriptor(),
                 this, &default_instance_,
                 _offsets_, _has_bits_, NULL),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

flow_collection::~flow_collection() {
  if (this != &default_instance_) {
  }
}

const ::google::protobuf::Descriptor* flow_collection::descriptor() {
  if (flow_collection_descriptor_ == NULL) proto_BuildDescriptors_flowcollection_2eproto();
  return flow_collection_descriptor_;
}

flow_collection* flow_collection::New() const {
  return new flow_collection;
}

const ::google::protobuf::Descriptor* flow_collection::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Message::Reflection*
flow_collection::GetReflection() const {
  return &_reflection_;
}

::google::protobuf::Message::Reflection* flow_collection::GetReflection() {
  return &_reflection_;
}
