// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "PacketStatistic.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

#include "PacketDigest.h"
#include "classifier.h"

namespace {

const ::google::protobuf::Descriptor* CPacketStatistic_descriptor_ = NULL;

}  // namespace

ResultEnum CPacketStatistic::AddPacketInfo(const CPacketDigest* pDigest )
{
	ResultEnum rs = eOK;
	++m_llpacketnumber_;
	m_lltrafficvolume_ += pDigest->getPacketSize();
	if (CClassifier::IsP2P(pDigest->getProtocolClassification()))
	{
		++m_llp2ppacketnumber_;
		m_llp2ptrafficvolume_ += pDigest->getPacketSize();
	}
	return rs;
}


void proto_BuildDescriptors_PacketStatistic_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  const ::google::protobuf::FileDescriptor* file = pool->InternalBuildGeneratedFile(
    "\n\025PacketStatistic.proto\"\241\003\n\020CPacketStati"
    "stic\022\030\n\020m_llPacketNumber\030\001 \002(\006\022\031\n\021m_llTr"
    "afficVolume\030\002 \002(\006\022\035\n\025m_llEmptyPacketNumb"
    "er\030\003 \002(\006\022\033\n\023m_llTCPPacketNumber\030\004 \002(\006\022\034\n"
    "\024m_llTCPTrafficVolume\030\005 \002(\006\022\033\n\023m_llUDPPa"
    "cketNumber\030\006 \002(\006\022\034\n\024m_llUDPTrafficVolume"
    "\030\007 \002(\006\022\033\n\023m_llP2PPacketNumber\030\010 \002(\006\022\034\n\024m"
    "_llP2PTrafficVolume\030\t \002(\006\022\034\n\024m_llHTTPPac"
    "ketNumber\030\n \002(\006\022\035\n\025m_llHTTPTrafficVolume"
    "\030\013 \002(\006\022$\n\034m_llUnidentifiedPacketNumber\030\014"
    " \002(\006\022%\n\035m_llUnidentifiedTrafficVolume\030\r "
    "\002(\006", 443);
  CPacketStatistic_descriptor_ = file->message_type(0);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CPacketStatistic_descriptor_, &CPacketStatistic::default_instance());
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PacketStatistic_2eproto {
  StaticDescriptorInitializer_PacketStatistic_2eproto() {
    proto_BuildDescriptors_PacketStatistic_2eproto();
  }
} static_descriptor_initializer_PacketStatistic_2eproto_;


// ===================================================================

const CPacketStatistic CPacketStatistic::default_instance_;














const int CPacketStatistic::_offsets_[13] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_llpacketnumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_lltrafficvolume_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_llemptypacketnumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_lltcppacketnumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_lltcptrafficvolume_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_lludppacketnumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_lludptrafficvolume_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_llp2ppacketnumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_llp2ptrafficvolume_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_llhttppacketnumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_llhttptrafficvolume_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_llunidentifiedpacketnumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CPacketStatistic, m_llunidentifiedtrafficvolume_),
};

CPacketStatistic::CPacketStatistic()
  : _reflection_(descriptor(),
                 this, &default_instance_,
                 _offsets_, _has_bits_, NULL),
    _cached_size_(0),
    m_llpacketnumber_(GOOGLE_ULONGLONG(0)),
    m_lltrafficvolume_(GOOGLE_ULONGLONG(0)),
    m_llemptypacketnumber_(GOOGLE_ULONGLONG(0)),
    m_lltcppacketnumber_(GOOGLE_ULONGLONG(0)),
    m_lltcptrafficvolume_(GOOGLE_ULONGLONG(0)),
    m_lludppacketnumber_(GOOGLE_ULONGLONG(0)),
    m_lludptrafficvolume_(GOOGLE_ULONGLONG(0)),
    m_llp2ppacketnumber_(GOOGLE_ULONGLONG(0)),
    m_llp2ptrafficvolume_(GOOGLE_ULONGLONG(0)),
    m_llhttppacketnumber_(GOOGLE_ULONGLONG(0)),
    m_llhttptrafficvolume_(GOOGLE_ULONGLONG(0)),
    m_llunidentifiedpacketnumber_(GOOGLE_ULONGLONG(0)),
    m_llunidentifiedtrafficvolume_(GOOGLE_ULONGLONG(0)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (this == &default_instance_) {
  }
}

CPacketStatistic::CPacketStatistic(const CPacketStatistic& from)
  : _reflection_(descriptor(),
                 this, &default_instance_,
                 _offsets_, _has_bits_, NULL),
    _cached_size_(0),
    m_llpacketnumber_(GOOGLE_ULONGLONG(0)),
    m_lltrafficvolume_(GOOGLE_ULONGLONG(0)),
    m_llemptypacketnumber_(GOOGLE_ULONGLONG(0)),
    m_lltcppacketnumber_(GOOGLE_ULONGLONG(0)),
    m_lltcptrafficvolume_(GOOGLE_ULONGLONG(0)),
    m_lludppacketnumber_(GOOGLE_ULONGLONG(0)),
    m_lludptrafficvolume_(GOOGLE_ULONGLONG(0)),
    m_llp2ppacketnumber_(GOOGLE_ULONGLONG(0)),
    m_llp2ptrafficvolume_(GOOGLE_ULONGLONG(0)),
    m_llhttppacketnumber_(GOOGLE_ULONGLONG(0)),
    m_llhttptrafficvolume_(GOOGLE_ULONGLONG(0)),
    m_llunidentifiedpacketnumber_(GOOGLE_ULONGLONG(0)),
    m_llunidentifiedtrafficvolume_(GOOGLE_ULONGLONG(0)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

CPacketStatistic::~CPacketStatistic() {
  if (this != &default_instance_) {
  }
}

const ::google::protobuf::Descriptor* CPacketStatistic::descriptor() {
  if (CPacketStatistic_descriptor_ == NULL) proto_BuildDescriptors_PacketStatistic_2eproto();
  return CPacketStatistic_descriptor_;
}

CPacketStatistic* CPacketStatistic::New() const {
  return new CPacketStatistic;
}

const ::google::protobuf::Descriptor* CPacketStatistic::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Message::Reflection*
CPacketStatistic::GetReflection() const {
  return &_reflection_;
}

::google::protobuf::Message::Reflection* CPacketStatistic::GetReflection() {
  return &_reflection_;
}
