// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "packetDigest.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* packet_digest_descriptor_ = NULL;

}  // namespace


void proto_BuildDescriptors_packetDigest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  const ::google::protobuf::FileDescriptor* file = pool->InternalBuildGeneratedFile(
    "\n\022packetDigest.proto\"\206\001\n\rpacket_digest\022\022"
    "\n\ntime_stamp\030\001 \002(\r\022\020\n\010src_addr\030\002 \002(\r\022\020\n\010"
    "dst_addr\030\003 \002(\r\022\023\n\013packet_size\030\004 \002(\r\022\020\n\010p"
    "rotocol\030\005 \002(\r\022\026\n\016protocol_class\030\006 \002(\r", 157);
  packet_digest_descriptor_ = file->message_type(0);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    packet_digest_descriptor_, &packet_digest::default_instance());
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_packetDigest_2eproto {
  StaticDescriptorInitializer_packetDigest_2eproto() {
    proto_BuildDescriptors_packetDigest_2eproto();
  }
} static_descriptor_initializer_packetDigest_2eproto_;


// ===================================================================

const packet_digest packet_digest::default_instance_;







const int packet_digest::_offsets_[6] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(packet_digest, time_stamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(packet_digest, src_addr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(packet_digest, dst_addr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(packet_digest, packet_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(packet_digest, protocol_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(packet_digest, protocol_class_),
};

packet_digest::packet_digest()
  : _reflection_(descriptor(),
                 this, &default_instance_,
                 _offsets_, _has_bits_, NULL),
    _cached_size_(0),
    time_stamp_(0u),
    src_addr_(0u),
    dst_addr_(0u),
    packet_size_(0u),
    protocol_(0u),
    protocol_class_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (this == &default_instance_) {
  }
}

packet_digest::packet_digest(const packet_digest& from)
  : _reflection_(descriptor(),
                 this, &default_instance_,
                 _offsets_, _has_bits_, NULL),
    _cached_size_(0),
    time_stamp_(0u),
    src_addr_(0u),
    dst_addr_(0u),
    packet_size_(0u),
    protocol_(0u),
    protocol_class_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

packet_digest::~packet_digest() {
  if (this != &default_instance_) {
  }
}

const ::google::protobuf::Descriptor* packet_digest::descriptor() {
  if (packet_digest_descriptor_ == NULL) proto_BuildDescriptors_packetDigest_2eproto();
  return packet_digest_descriptor_;
}

packet_digest* packet_digest::New() const {
  return new packet_digest;
}

const ::google::protobuf::Descriptor* packet_digest::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Message::Reflection*
packet_digest::GetReflection() const {
  return &_reflection_;
}

::google::protobuf::Message::Reflection* packet_digest::GetReflection() {
  return &_reflection_;
}
